{
 "title": "PurpleAirAPI (PAA) Data Logger Grafana Dashboard",
 "description": "PurpleAirAPI (PAA) Data Logger Grafana Dashboard",
 "time": { "from": "now-15m", "to": "now" },
 "templating": {
  "list": [
   {
    "name": "name_and_sensor_index",
    "label": "Sensor Name and Index",
    "query": "WITH concated_results AS (\nSELECT DISTINCT sensor_index, name , CONCAT(name,  ', ' ,sensor_index) \"Concated sensor_index and name\"\nFROM sensor_index_and_name_1hour_aggregate\nORDER BY sensor_index ASC\n)\n\nSELECT \"Concated sensor_index and name\" FROM concated_results;"
   },
   {
    "name": "sensor_index",
    "label": "sensor_index",
    "query": "WITH unconcated_results AS (\nSELECT string_to_array('$name_and_sensor_index', ', ') AS parts\n)\nSELECT parts[2] FROM unconcated_results;"
   }
  ]
 },
 "panels": [
  {
   "title": "Miscellaneous Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 },
   "collapsed": true,
   "panels": [
    {
     "title": "Miscellaneous Fields",
     "type": "timeseries",
     "description": "Miscellaneous Fields",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(voc) AS \"voc\",\n  max(voc_a) AS \"voc_a\",\n  max(voc_b) AS \"voc_b\",\n  max(ozone1) AS \"ozone1\",\n  max(analog_input) AS \"analog_input\"\nFROM miscellaneous_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Particle Count Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 1 },
   "collapsed": true,
   "panels": [
    {
     "title": "Particle Count Fields",
     "type": "timeseries",
     "description": "Particle Ccount Fields",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 2 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(um_count_0_3) AS \"um_count_0_3\",\n  max(um_count_a_0_3) AS \"um_count_a_0_3\",\n  max(um_count_b_0_3) AS \"um_count_b_0_3\",\n  max(um_count_0_5) AS \"um_count_0_5\",\n  max(um_count_a_0_5) AS \"um_count_a_0_5\",\n  max(um_count_b_0_5) AS \"um_count_b_0_5\",\n  max(um_count_1_0) AS \"um_count_1_0\",\n  max(um_count_a_1_0) AS \"um_count_a_1_0\",\n  max(um_count_b_1_0) AS \"um_count_b_1_0\",\n  max(um_count_2_5) AS \"um_count_2_5\",\n  max(um_count_a_2_5) AS \"um_count_a_2_5\",\n  max(um_count_b_2_5) AS \"um_count_b_2_5\",\n  max(um_count_5_0) AS \"um_count_5_0\",\n  max(um_count_a_5_0) AS \"um_count_a_5_0\",\n  max(um_count_b_5_0) AS \"um_count_b_5_0\",\n  max(um_count_10_0) AS \"um_count_10_0\",\n  max(um_count_a_10_0) AS \"um_count_a_10_0\",\n  max(um_count_b_10_0) AS \"um_count_b_10_0\"\nFROM particle_count_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "PM10.0 Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 2 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM10.0 Fields",
     "type": "timeseries",
     "description": "PM10.0 Fields",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(pm10_0) AS \"pm10_0\",\n  max(pm10_0_a) AS \"pm10_0_a\",\n  max(pm10_0_b) AS \"pm10_0_b\",\n  max(pm10_0_atm) AS \"pm10_0_atm\",\n  max(pm10_0_atm_a) AS \"pm10_0_atm_a\",\n  max(pm10_0_atm_b) AS \"pm10_0_atm_b\",\n  max(pm10_0_cf_1) AS \"pm10_0_cf_1\",\n  max(pm10_0_cf_1_a) AS \"pm10_0_cf_1_a\",\n  max(pm10_0_cf_1_b) AS \"pm10_0_cf_1_b\"\nFROM pm10_0_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Station Information And Status Fields: Text - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 3 },
   "collapsed": true,
   "panels": [
    {
     "title": "Station Information And Status Fields: Text",
     "type": "table",
     "description": "Station Information And Status Fields: Text",
     "gridPos": { "h": 8, "w": 24, "x": 0, "y": 4 },
     "targets": [
      {
       "rawSql": "SELECT\n  data_time_stamp AS \"time\",\n  name AS \"name\",\n  model AS \"model\",\n  hardware AS \"hardware\",\n  last_seen AS \"last_seen\",\n  last_modified AS \"last_modified\",\n  date_created AS \"date_created\"\nFROM station_information_and_status_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Environmental Fields - for: $sensor_index, $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 4 },
   "collapsed": true,
   "panels": [
    {
     "title": "Environmental Fields",
     "type": "timeseries",
     "description": "Environmental Fields",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 1 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(humidity) AS \"humidity\",\n  max(humidity_a) AS \"humidity_a\",\n  max(humidity_b) AS \"humidity_b\",\n  max(pressure) AS \"pressure\",\n  max(pressure_a) AS \"pressure_a\",\n  max(pressure_b) AS \"pressure_b\",\n  max(temperature) AS \"temperature\",\n  max(temperature_a) AS \"temperature_a\",\n  max(temperature_b) AS \"temperature_b\"\nFROM environmental_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "PM1.0 Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 5 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM1.0 Fields",
     "type": "timeseries",
     "description": "PM1.0 Fields",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 6 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(pm1_0) AS \"pm1_0\",\n  max(pm1_0_a) AS \"pm1_0_a\",\n  max(pm1_0_b) AS \"pm1_0_b\",\n  max(pm1_0_atm) AS \"pm1_0_atm\",\n  max(pm1_0_atm_a) AS \"pm1_0_atm_a\",\n  max(pm1_0_atm_b) AS \"pm1_0_atm_b\",\n  max(pm1_0_cf_1) AS \"pm1_0_cf_1\",\n  max(pm1_0_cf_1_a) AS \"pm1_0_cf_1_a\",\n  max(pm1_0_cf_1_b) AS \"pm1_0_cf_1_b\"\nFROM pm1_0_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "PM2.5 Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 6 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM2.5 Fields",
     "type": "timeseries",
     "description": "PM2.5 Fields",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 7 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(pm2_5_alt) AS \"pm2_5_alt\",\n  max(pm2_5_alt_a) AS \"pm2_5_alt_a\",\n  max(pm2_5_alt_b) AS \"pm2_5_alt_b\",\n  max(pm2_5) AS \"pm2_5\",\n  max(pm2_5_a) AS \"pm2_5_a\",\n  max(pm2_5_b) AS \"pm2_5_b\",\n  max(pm2_5_atm) AS \"pm2_5_atm\",\n  max(pm2_5_atm_a) AS \"pm2_5_atm_a\",\n  max(pm2_5_atm_b) AS \"pm2_5_atm_b\",\n  max(pm2_5_cf_1) AS \"pm2_5_cf_1\",\n  max(pm2_5_cf_1_a) AS \"pm2_5_cf_1_a\",\n  max(pm2_5_cf_1_b) AS \"pm2_5_cf_1_b\"\nFROM pm2_5_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "PM2.5 Pseudo Average Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 7 },
   "collapsed": true,
   "panels": [
    {
     "title": "PM2.5 Pseudo Average Fields",
     "type": "timeseries",
     "description": "PM2.5 Pseudo Average Fields",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 8 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(pm2_5_10minute) AS \"pm2_5_10minute\",\n  max(pm2_5_10minute_a) AS \"pm2_5_10minute_a\",\n  max(pm2_5_10minute_b) AS \"pm2_5_10minute_b\",\n  max(pm2_5_30minute) AS \"pm2_5_30minute\",\n  max(pm2_5_30minute_a) AS \"pm2_5_30minute_a\",\n  max(pm2_5_30minute_b) AS \"pm2_5_30minute_b\",\n  max(pm2_5_60minute) AS \"pm2_5_60minute\",\n  max(pm2_5_60minute_a) AS \"pm2_5_60minute_a\",\n  max(pm2_5_60minute_b) AS \"pm2_5_60minute_b\",\n  max(pm2_5_6hour) AS \"pm2_5_6hour\",\n  max(pm2_5_6hour_a) AS \"pm2_5_6hour_a\",\n  max(pm2_5_6hour_b) AS \"pm2_5_6hour_b\",\n  max(pm2_5_24hour) AS \"pm2_5_24hour\",\n  max(pm2_5_24hour_a) AS \"pm2_5_24hour_a\",\n  max(pm2_5_24hour_b) AS \"pm2_5_24hour_b\",\n  max(pm2_5_1week) AS \"pm2_5_1week\",\n  max(pm2_5_1week_a) AS \"pm2_5_1week_a\",\n  max(pm2_5_1week_b) AS \"pm2_5_1week_b\"\nFROM pm2_5_pseudo_average_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Station Information And Status Fields: Numbers - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 8 },
   "collapsed": true,
   "panels": [
    {
     "title": "Station Information And Status Fields: Numbers",
     "type": "timeseries",
     "description": "Station Information And Status Fields: Numbers",
     "gridPos": { "h": 9, "w": 24, "x": 0, "y": 9 },
     "targets": [
      {
       "rawSql": "SELECT\n  $__timeGroupAlias(data_time_stamp,$__interval),\n  max(icon) AS \"icon\",\n  max(location_type) AS \"location_type\",\n  max(private) AS \"private\",\n  max(latitude) AS \"latitude\",\n  max(longitude) AS \"longitude\",\n  max(altitude) AS \"altitude\",\n  max(position_rating) AS \"position_rating\",\n  max(led_brightness) AS \"led_brightness\",\n  max(rssi) AS \"rssi\",\n  max(uptime) AS \"uptime\",\n  max(pa_latency) AS \"pa_latency\",\n  max(memory) AS \"memory\",\n  max(channel_state) AS \"channel_state\",\n  max(channel_flags) AS \"channel_flags\",\n  max(channel_flags_manual) AS \"channel_flags_manual\",\n  max(channel_flags_auto) AS \"channel_flags_auto\",\n  max(confidence) AS \"confidence\",\n  max(confidence_manual) AS \"confidence_manual\",\n  max(confidence_auto) AS \"confidence_auto\"\nFROM station_information_and_status_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nGROUP BY 1\nORDER BY 1"
      }
     ]
    }
   ]
  },
  {
   "title": "Thingspeal Fields - for: $name_and_sensor_index",
   "type": "row",
   "gridPos": { "h": 1, "w": 24, "x": 0, "y": 9 },
   "collapsed": true,
   "panels": [
    {
     "title": "Thingspeak Fields",
     "type": "table",
     "description": "Thingspeak Fields",
     "gridPos": { "h": 10, "w": 24, "x": 0, "y": 10 },
     "targets": [
      {
       "rawSql": "SELECT\n  data_time_stamp AS \"time\",\n  primary_id_a,\n  secondary_id_a,\n  primary_id_b,\n  primary_key_b,\n  secondary_id_b,\n  secondary_key_b\nFROM thingspeak_fields\nWHERE\n  $__timeFilter(data_time_stamp) AND\n  sensor_index = $sensor_index\nORDER BY 1"
      }
     ]
    }
   ]
  }
 ]
}