# Refer to the following link for help
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: TestPyPI Distributions
permissions:
  contents: read
concurrency: build_and_publish_to_test_pypi
on:
  push:
    branches: [ main ]

jobs:
  check-source-changes:
    runs-on: ubuntu-latest
    outputs:
      run_job: ${{ steps.changed-files.outputs.any_changed }}
    steps:
      - name: Checkout Sourcecode
        uses: actions/checkout@v7

      - name: Check for changes in setup.py/cfg
        id: changed-files
        uses: tj-actions/changed-files@v47.0.6
        with:
          files: |
            .github/workflows/build_and_publish_to_test_pypi.yml
            .github/actions/build-and-publish-distribution/action.yml
            setup.py
            setup.cfg

  build-n-publish-test-pypi:
    name: Build and Publish To Test PyPi
    runs-on: ubuntu-latest
    environment: build_and_publish_to_test_pypi
    permissions:
      id-token: write
    needs: check-source-changes
    if: needs.check-source-changes.outputs.run_job == 'true'

    steps:
      - uses: actions/checkout@v7
      - name: Build and Publish Distribution
        uses: ./.github/actions/build-and-publish-distribution
        with:
          target: "test_pypi"
