# Refer to the following link for help
# https://packaging.python.org/en/latest/guides/publishing-package-distribution-releases-using-github-actions-ci-cd-workflows/

name: PyPI Distributions
concurrency:
  group: build_and_publish_to_pypi
  cancel-in-progress: true

on:
  release:
    types: [published]
  workflow_dispatch:

jobs:
  build-n-publish-pypi:
    name: Build and Publish
    runs-on: ubuntu-latest
    environment: build_and_publish_to_pypi
    permissions:
      contents: read
      id-token: write

    steps:
      - uses: actions/checkout@v7
      - name: Build and Publish Distribution
        uses: ./.github/actions/build-and-publish-distribution
        with:
          target: "pypi"
          pypi-token: ${{ secrets.PYPI_API_TOKEN }}
